site_name: Way Project Documentation
site_description: Documentation for the Way project
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

# The docs directory is now a sibling of the config file
docs_dir: docs

nav:
  - Documentation:
    - Overview: documentation/overview.md
    - Development:
      - Setup: documentation/development/setup.md
      - Architecture: documentation/development/architecture.md
    - API:
      - Overview: documentation/api/overview.md
      - Endpoints: documentation/api/endpoints.md
  - Current:
    - Methodology: current/methodology.md
    - Results:
      - Search: current/results/01-search.md
      - Select: current/results/02-select.md
      - Define: current/results/03-define.md
      - Plan: current/results/04-plan.md
      - Do: current/results/05-do.md
      - Check: current/results/06-check.md
      - Act: current/results/07-act.md
  - Guardrails:
    - Standards: guardrails/standards.md
    - Best Practices: guardrails/best-practices.md
    - Code Review: guardrails/code-review.md
    - Security: guardrails/security.md
  - Project History:
    - Timeline: history/timeline.md
    - Decisions: history/decisions.md
    - Milestones: history/milestones.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - footnotes
